<?php

return [
    'portal' => [
        'titulo_depositante' => 'Depósitos',
    ],
    'general' => [
        'titulo' => 'Solicitud de depósito',
        'intro' => 'Completa el expediente; el avance se guarda por etapas.',
        'atras' => 'Atrás',
    ],
    'tramite' => [
        'titulo' => 'Tipo de trámite',
        'intro' => 'Indica si el material permanecerá temporalmente en custodia o pasará a formar parte definitiva de la colección.',
        'deposito' => 'Custodia temporal con devolución programada.',
        'donacion' => 'Cesión definitiva al patrimonio de la colección. Requiere carta de cesión de derechos.',
        'accion' => 'Continuar',
        'aviso_deposito' => 'El depósito es temporal. Los especímenes permanecerán en custodia y serán devueltos según el acta correspondiente.',
        'aviso_donacion' => 'La donación transfiere permanentemente la propiedad de los especímenes a la colección. Se requiere carta de cesión de derechos firmada.',
        'documentos_titulo' => 'Documentos que necesitarás',
        'requisito_deposito_solicitud' => 'Solicitud de depósito generada y firmada dentro de HubDigital',
        'requisito_deposito_permisos' => 'Autorización de recolección y/o permiso de movilización según el origen',
        'requisito_deposito_carta' => 'Carta de procedencia o justificación según la situación regulatoria',
        'requisito_datos' => 'Datos de depósito material MEPN y detalle biológico, completados mediante formularios guiados',
        'nota_requisitos' => 'Los documentos exactos se determinarán en el siguiente paso según el origen de los especímenes.',
        'requisito_donacion_solicitud' => 'Solicitud de donación generada y firmada dentro de HubDigital',
        'requisito_donacion_carta' => 'Carta de cesión de derechos / origen lícito',
    ],
    'origen' => [
        'titulo' => 'Origen de los especímenes',
        'intro' => 'Declara la procedencia y situación regulatoria. Con estas respuestas determinaremos los documentos que debes adjuntar.',
        'nacional' => 'Especímenes recolectados dentro del territorio ecuatoriano.',
        'exterior' => 'Provenientes de una colección o expedición fuera del país.',
        'accion' => 'Guardar y continuar',
        'con_permisos' => 'Cuenta con autorización vigente de recolección y permiso de movilización emitidos por el MAE.',
        'sin_permisos' => 'Solo dispone de carta de justificación institucional o personal que explica la ausencia de permisos.',
        'pichincha' => 'Los especímenes fueron recolectados en la provincia de Pichincha.',
        'otra_provincia' => 'Los especímenes provienen de otra provincia del Ecuador.',
        'aviso_exterior' => 'Para especímenes del exterior se requiere una carta de procedencia firmada por el responsable de la colección de origen.',
    ],
    'documentos' => [
        'titulo' => 'Documentos oficiales',
        'intro_con_archivos' => 'Adjunta los PDF indicados. HubDigital verificará su contenido y que pertenezcan al mismo expediente.',
        'intro_sin_archivos' => 'Esta modalidad genera internamente la solicitud y sus declaraciones; no necesitas adjuntar archivos en este paso.',
        'ayuda_archivos' => 'Puedes cargarlos con cualquier nombre; validaremos el tipo mediante su contenido.',
        'accion_con_archivos' => 'Validar documentos',
        'accion_sin_archivos' => 'Confirmar y continuar',
        'pausa_explicacion' => 'La carga de documentos ha sido pausada. El funcionario responsable revisará tu caso y se pondrá en contacto contigo para orientarte.',
        'asistencia_explicacion' => 'Solicita orientación si no puedes aportar ninguno de los archivos indicados.',
        'sin_archivos_explicacion' => 'Confirma este estado y continúa con los datos oficiales del expediente.',
        'asistencia_accion' => 'Solicitar asistencia',
        'ayuda_formato_deposito' => 'Formulario oficial de la colección que debes completar para iniciar tu solicitud. El ejemplo de referencia te muestra cómo luce correctamente llenado.',
        'ayuda_formato_donacion' => 'Formulario oficial para formalizar la transferencia permanente de los especímenes. Consulta el ejemplo de referencia para ver cómo debe quedar.',
        'ayuda_autorizacion' => 'Oficio emitido por el Ministerio del Ambiente que concede la autorización de recolección. El sistema extraerá el número, titular, organización, proyecto, grupos biológicos, fechas y firma.',
        'ayuda_movilizacion' => 'Guía que ampara el traslado. El sistema extraerá su número, autorización relacionada, vigencia, origen, destino y códigos de muestra para llenar la matriz.',
        'ayuda_justificacion' => 'Carta redactada por ti o tu institución que explica por qué no cuentas con permisos del MAE. El ejemplo te muestra el tipo de contenido y tono esperados.',
        'ayuda_procedencia' => 'Este documento explica y justifica cómo obtuviste los especímenes que deseas depositar. Debe incluir el origen, la procedencia y cualquier información que respalde la legalidad de su obtención.',
        'ayuda_cesion' => 'Documento que certifica que los especímenes se donan voluntariamente y que su obtención fue legal. El ejemplo te orienta sobre su contenido.',
        'ayuda_delegacion' => 'Si el nombre en los documentos no coincide con tu perfil, adjunta esta carta explicando el motivo o autorizando a otra persona a realizar el trámite.',
    ],
    'datos' => [
        'titulo' => 'Datos del depósito de material MEPN',
        'intro' => 'Completa dentro de HubDigital los datos del depósito de material MEPN. El sistema recupera lo posible de tus documentos y te pide confirmar el resultado.',
        'perfil' => 'Se toman de tu perfil autenticado para evitar volver a digitarlos.',
        'accion' => 'Continuar',
        'material_explicacion' => 'Permisos, grupo biológico, cantidades y localidades. Estos datos son responsabilidad del consultor.',
        'uso_interno_explicacion' => 'Proceso interno, fecha de recepción, período, observaciones y estado serán completados por el receptor y la curaduría. El consultor no puede modificarlos.',
        'manual_explicacion' => 'Completa manualmente los campos marcados abajo para continuar.',
        'sin_firma_explicacion' => 'Puedes continuar, pero el funcionario responsable revisará los documentos antes de aprobar la solicitud.',
        'firma_no_verificada' => 'El sistema no pudo comprobar la firma electrónica. Vuelve al paso anterior y carga nuevamente los documentos.',
        'discrepancia_menor' => 'Hay una diferencia menor entre tu nombre de perfil y el nombre del documento. Puedes continuar, pero se recomienda corregir el nombre en tu perfil de usuario.',
        'discrepancia_mayor' => 'El nombre del documento y el del perfil difieren considerablemente. Elige una opción:',
        'carta_delegacion' => 'O adjunta la carta de delegación si gestionas el trámite a nombre de otra persona.',
        'nombres_coinciden' => 'Los nombres coinciden correctamente. Puedes continuar con el trámite.',
    ],
    'detalle' => [
        'titulo' => 'Detalle biológico asistido',
        'intro' => 'A partir de los datos MEPN y los códigos leídos en la guía, registra cada espécimen o lote. HubDigital normaliza el resultado internamente a Darwin Core y lo contrasta con GBIF.',
        'accion' => 'Revisar y enviar',
        'codigos_explicacion' => 'Selecciona un código para trasladarlo sin volver a digitarlo. HubDigital no inventa la identificación taxonómica: debes elegirla del catálogo.',
        'taxon_explicacion' => 'Solo se acepta una opción seleccionada del catálogo EPN o de GBIF Backbone.',
        'permiso_investigacion' => 'Leído y confirmado desde la autorización.',
        'permiso_transporte' => 'Leído y confirmado desde la guía.',
        'validando' => 'Validando campos Darwin Core y consistencia taxonómica contra GBIF...',
    ],
    'envio' => [
        'titulo' => 'Revisar, firmar y enviar',
        'intro' => 'Comprueba la información, genera el documento institucional y fírmalo antes de remitir el expediente al equipo curatorial.',
        'plazo' => 'Tu solicitud será evaluada por curaduría en máximo 3 días hábiles. Recibirás notificación en cada cambio de estado.',
        'accion' => 'Enviar solicitud',
        'certificado_explicacion' => 'El certificado se abre localmente en un proceso aislado de tu navegador.',
        'clave_explicacion' => 'La contraseña nunca se transmite ni se almacena.',
        'copia_firmada' => 'La copia firmada quedó sellada con huella SHA-256 en el expediente.',
    ],
];
